package com.briup.apps.poll.bean;

public class Answer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_answer.id
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_answer.selections
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    private String selections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_answer.checkes
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    private String checkes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_answer.content
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poll_answer.Column1
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    private String column1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_answer.id
     *
     * @return the value of poll_answer.id
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_answer.id
     *
     * @param id the value for poll_answer.id
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_answer.selections
     *
     * @return the value of poll_answer.selections
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    public String getSelections() {
        return selections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_answer.selections
     *
     * @param selections the value for poll_answer.selections
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    public void setSelections(String selections) {
        this.selections = selections == null ? null : selections.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_answer.checkes
     *
     * @return the value of poll_answer.checkes
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    public String getCheckes() {
        return checkes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_answer.checkes
     *
     * @param checkes the value for poll_answer.checkes
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    public void setCheckes(String checkes) {
        this.checkes = checkes == null ? null : checkes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_answer.content
     *
     * @return the value of poll_answer.content
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_answer.content
     *
     * @param content the value for poll_answer.content
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poll_answer.Column1
     *
     * @return the value of poll_answer.Column1
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poll_answer.Column1
     *
     * @param column1 the value for poll_answer.Column1
     *
     * @mbg.generated Mon Jun 25 21:58:43 CST 2018
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }
}